services:
  mongodb:
    image: mongo:5
    env_file: ./.env
    volumes: 
     - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT

  server:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
     - ./:/app
    ports:
      - $SERVER_LOCAL_PORT:$SERVER_DOCKER_PORT
    environment:
      - DB_HOST=$MONGODB_HOST
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT

  client: 
    depends_on:
      - server
    build: 
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
     - ./client:/app/client
     - ./shared:/app/shared
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
    
volumes:
  db: 